name: core_testing
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  injectable: ^2.3.2
  get_it: ^7.6.7

  di:
    path: '../di'
  domain:
    path: '../domain'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  mockito: ^5.4.4


flutter:

