name: app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # current module dependencies
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  get: ^4.6.6
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  go_router: ^13.2.0
  flutter_svg: ^2.0.10
  syncfusion_flutter_charts: ^27.2.5



  # shared
  injectable: ^2.3.2
  get_it: ^7.6.7
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1


# projects
  domain:
    path: '../domain'
  di:
    path: '../di'
  core_testing:
    path: '../core_testing'
  data:
    path: '../data'


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: any
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  mockito: ^5.4.4
  bdd_widget_test: ^1.7.4


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
