// Mocks generated by Mockito 5.4.4 from annotations
// in data/test/src/orders_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:data/src/repository/orders/orders_data_store.dart' as _i2;
import 'package:data/src/store/orders/orders_data_store_factory.dart' as _i3;
import 'package:domain/domain.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrdersDataStore_0 extends _i1.SmartFake
    implements _i2.OrdersDataStore {
  _FakeOrdersDataStore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrdersDataStoreFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersDataStoreFactory extends _i1.Mock
    implements _i3.OrdersDataStoreFactory {
  @override
  _i2.OrdersDataStore getRemote() => (super.noSuchMethod(
        Invocation.method(
          #getRemote,
          [],
        ),
        returnValue: _FakeOrdersDataStore_0(
          this,
          Invocation.method(
            #getRemote,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeOrdersDataStore_0(
          this,
          Invocation.method(
            #getRemote,
            [],
          ),
        ),
      ) as _i2.OrdersDataStore);
}

/// A class which mocks [OrdersDataStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersDataStore extends _i1.Mock implements _i2.OrdersDataStore {
  @override
  _i4.Future<List<_i5.OrderModel>> getOrders() => (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
        ),
        returnValue: _i4.Future<List<_i5.OrderModel>>.value(<_i5.OrderModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.OrderModel>>.value(<_i5.OrderModel>[]),
      ) as _i4.Future<List<_i5.OrderModel>>);
}
