name: di
description: A new Flutter package project
version: 0.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.3.2
  get_it: ^7.6.7

  # local packages
  app:
    path: '../app'
  domain:
    path: '../domain'
  data:
    path: '../data'



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: any
  injectable_generator: ^2.4.1

flutter:

